services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: studentdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Tanatswa@1212

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: studentdb
      MYSQL_ROOT_PASSWORD: Tanatswa@1212
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
